apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    dashboards: grafana
    folders: grafana-a
  name: grafana-a
  namespace: monitoring-stack
spec:
  client:
    preferIngress: false
  config:
    auth:
      disable_login_form: 'False'
      disable_signout_menu: 'True'
    auth.anonymous:
      enabled: 'True'
    auth.basic:
      enabled: 'True'
    auth.proxy:
      enable_login_token: 'True'
      enabled: 'True'
      header_name: X-Forwarded-User
      header_property: username
    log:
      mode: console
    users:
      auto_assign_org_role: Admin
  deployment:
    metadata: {}
    spec:
      template:
        metadata: {}
        spec:
          containers:
            - args:
                - '-provider=openshift'
                - '-pass-basic-auth=false'
                - '-https-address=:9091'
                - '-http-address='
                - '-email-domain=*'
                - '-upstream=http://localhost:3000'
                - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
                - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
                - '-tls-cert=/etc/tls/private/tls.crt'
                - '-tls-key=/etc/tls/private/tls.key'
                - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
                - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
                - '-openshift-service-account=grafana-a-sa'
                - '-openshift-ca=/etc/pki/tls/cert.pem'
                - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
                - '-openshift-ca=/etc/proxy/certs/ca-bundle.crt'
                - '-skip-auth-regex=^/metrics'
              image: quay.io/openshift/origin-oauth-proxy
              name: grafana-proxy
              ports:
                - containerPort: 9091
                  name: https
                  protocol: TCP
              resources: {}
              volumeMounts:
                - mountPath: /etc/tls/private
                  name: grafana-tls
                - mountPath: /etc/proxy/secrets
                  name: grafana-proxy
                - mountPath: /etc/proxy/certs
                  name: ocp-injected-certs
          volumes:
            - name: grafana-tls
              secret:
                secretName: grafana-tls
            - name: grafana-proxy
              secret:
                secretName: grafana-proxy
            - configMap:
                name: ocp-injected-certs
              name: ocp-injected-certs
  route:
    metadata: {}
    spec:
      host: grafana-a-route.apps.sno.xforce.local
      port:
        targetPort: https
      tls:
        termination: reencrypt
      to:
        kind: Service
        name: grafana-a-service
        weight: 100
      wildcardPolicy: None
  service:
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: grafana-tls
    spec:
      ports:
        - name: https
          port: 9091
          protocol: TCP
          targetPort: https
  serviceAccount:
    metadata:
      annotations:
        serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-a-route"}}'
